{% set build = 0 %}
{% set version = "2.6" %}

package:
    name: tmux
    version: {{version}}

about:
    home: https://tmux.github.io
    license: MIT
    summary: terminal multiplexer

source:
    fn: tig-{{version}}.tar.gz
    url: https://github.com/tmux/tmux/releases/download/{{version}}/tmux-{{version}}.tar.gz
    md5: d541ff392249f94c4f3635793556f827

requirements:
    build:
        - libevent >=2.0
        - ncurses
    run:
        - libevent >=2.0
        - ncurses

build:
    number: {{build}}
