{% set build = 0 %}
{% set version = "2.2" %}

package:
    name: tmux
    version: {{version}}

about:
    home: https://tmux.github.io
    license: MIT
    summary: terminal multiplexer

source:
    fn: tig-{{version}}.tar.gz
    url: https://github.com/tmux/tmux/releases/download/{{version}}/tmux-{{version}}.tar.gz
    md5: bd95ee7205e489c62c616bb7af040099

requirements:
    build:
        - libevent >=2.0
    run:
        - libevent >=2.0

build:
    number: {{build}}
